---
- hosts: localhost
  become: true
  become_user: root
  become_method: su
  tasks:
    - name: Create admin group
      group:
        name: admin
        state: present
    
    - name: Create developers group
      group:
        name: developers
        state: present
    
    - name: Create testing group
      group:
        name: testing
        state: present
    
    - name: Add ad1 and ad2 to admin group
      user:
        name: "{{ item }}"
        groups: admin
      with_items:
        - ad1
        - ad2
    
    - name: Add dev1 and dev2 to developers group
      user:
        name: "{{ item }}"
        groups: developers
      with_items:
        - dev1
        - dev2
    
    - name: Add qa1 and qa2 to testing group
      user:
        name: "{{ item }}"
        groups: testing
      with_items:
        - qa1
        - qa2
    
    # - name: Grant admin group sudo privileges
    #   lineinfile:
    #     path: /etc/sudoers
    #     line: "%admin ALL=(ALL) NOPASSWD: ALL"
    #     state: present
    
    - name: Grant developers group access to /opt/myapp
      file:
        path: /opt/myapp
        owner: root
        group: developers
        mode: "0775"
        state: directory
    
    - name: Grant testing group access to /var/log/myapp
      file:
        path: /var/log/myapp
        owner: root
        group: testing
        mode: "0775"
        state: directory
